---
- !supmua.org,2006-10-01/Redwood/Maildir
  uri: maildir:/Users/cscorley/.mail/cscorley-gmail.com/INBOX
  usual: true
  archived: false
  sync_back: true
  id: 1
  labels:
  - gmail
- !supmua.org,2006-10-01/Redwood/Maildir
  uri: maildir:/Users/cscorley/.mail/cscorley-crimson.ua.edu/INBOX
  usual: true
  archived: false
  sync_back: true
  id: 3
  labels:
  - ua
- !supmua.org,2006-10-01/Redwood/Maildir
  uri: maildir:/Users/cscorley/.mail/cscorley-gmail.com/archive
  usual: true
  archived: true
  sync_back: true
  id: 2
  labels:
  - gmail
- !supmua.org,2006-10-01/Redwood/Maildir
  uri: maildir:/Users/cscorley/.mail/cscorley-crimson.ua.edu/archive
  usual: true
  archived: true
  sync_back: true
  id: 4
  labels:
  - ua
- !supmua.org,2006-10-01/Redwood/SentLoader {}
